import type { SpecialistDefinition } from "@/lib/contracts/specialist";

/**
 * Canonical initial specialist roles available in JARVIS.
 * Each role defines bounded capabilities, allowed skills, routing profiles, and execution constraints.
 */
export const DEFAULT_SPECIALISTS: readonly SpecialistDefinition[] = [
  {
    id: "research",
    displayName: "Research Specialist",
    role: "Deep information retrieval and knowledge synthesis across Obsidian vault notes, Drive files, persistent memory, and demo datasets. Focuses on gathering facts, cross-referencing information, and summarizing findings without modifying data.",
    preferredRoutingProfile: "reasoning",
    allowedSkills: ["research"],
    allowedCapabilities: [
      "search_vault",
      "read_note",
      "search_drive",
      "read_drive_file",
      "search_demo_data",
      "read_demo_item",
      "search_memory",
      "list_memory",
    ],
    maxExecutionTimeMs: 45000,
    concurrencyLimit: 2,
    userVisible: true,
    isTemporary: false,
  },
  {
    id: "coding",
    displayName: "Coding Specialist",
    role: "Technical inspection, code analysis, architecture assessment, and documentation synthesis. Investigates codebases, designs solutions, and explains system implementations.",
    preferredRoutingProfile: "coding",
    allowedSkills: ["research"],
    allowedCapabilities: [
      "search_vault",
      "read_note",
      "search_demo_data",
      "read_demo_item",
    ],
    maxExecutionTimeMs: 60000,
    concurrencyLimit: 2,
    userVisible: true,
    isTemporary: false,
  },
  {
    id: "productivity",
    displayName: "Productivity Specialist",
    role: "Daily agenda organization, meeting preparation, calendar inspection, and loose-ends tracking. Coordinates schedules, organizes briefings, and prepares upcoming meetings.",
    preferredRoutingProfile: "fast",
    allowedSkills: ["morning-briefing", "meeting-prep", "loose-ends"],
    allowedCapabilities: [
      "get_calendar_events",
      "search_vault",
      "read_note",
      "get_current_time",
      "search_gmail",
      "read_gmail",
    ],
    maxExecutionTimeMs: 30000,
    concurrencyLimit: 2,
    userVisible: true,
    isTemporary: false,
  },
  {
    id: "memory",
    displayName: "Memory Specialist",
    role: "Knowledge base retrieval, long-term memory lookup, personal preference indexing, and durable memory management. Preserves and recalls context across conversations.",
    preferredRoutingProfile: "fast",
    allowedSkills: ["capture-note"],
    allowedCapabilities: [
      "search_memory",
      "list_memory",
      "search_vault",
      "read_note",
    ],
    maxExecutionTimeMs: 30000,
    concurrencyLimit: 2,
    userVisible: true,
    isTemporary: false,
  },
  {
    id: "communications",
    displayName: "Communications Specialist",
    role: "Message drafting, correspondence summarization, communication history review, and email synthesis. Any proposed write actions strictly require human approval.",
    preferredRoutingProfile: "fast",
    allowedSkills: ["meeting-prep", "loose-ends"],
    allowedCapabilities: [
      "search_gmail",
      "read_gmail",
      "draft_email",
    ],
    maxExecutionTimeMs: 30000,
    concurrencyLimit: 2,
    userVisible: true,
    isTemporary: false,
  },
  {
    id: "frontend",
    displayName: "Frontend & UI/UX Specialist",
    role: "Frontend engineering, component architecture, modern UI design systems, responsive layouts, Tailwind CSS, animations, and accessibility.",
    preferredRoutingProfile: "coding",
    allowedSkills: [
      "frontend-design",
      "ui-design",
      "ui-ux-pro-max",
      "react-expert",
      "nextjs-developer",
      "nextjs-app-router-patterns",
      "tailwind-design-system",
      "vercel-composition-patterns",
      "vercel-react-best-practices",
      "web-design-guidelines",
      "remotion",
    ],
    allowedCapabilities: [
      "search_vault",
      "read_note",
      "search_demo_data",
      "read_demo_item",
      "list_documents",
      "read_document",
      "write_document",
    ],
    maxExecutionTimeMs: 60000,
    concurrencyLimit: 2,
    userVisible: true,
    isTemporary: false,
  },
  {
    id: "backend",
    displayName: "Backend & Systems Specialist",
    role: "Backend system design, REST and GraphQL APIs, database schemas, authentication patterns, server logic, and multi-language services (TypeScript, Go, Kotlin).",
    preferredRoutingProfile: "coding",
    allowedSkills: [
      "backend-patterns",
      "api-design-principles",
      "auth-implementation-patterns",
      "typescript-pro",
      "golang-pro",
      "go-concurrency-patterns",
      "kotlin-specialist",
      "smart-file-code-organizer",
    ],
    allowedCapabilities: [
      "search_vault",
      "read_note",
      "search_demo_data",
      "read_demo_item",
      "list_documents",
      "read_document",
      "write_document",
    ],
    maxExecutionTimeMs: 60000,
    concurrencyLimit: 2,
    userVisible: true,
    isTemporary: false,
  },
  {
    id: "quality",
    displayName: "Quality & Testing Specialist",
    role: "Software quality assurance, systematic debugging, test-driven development (TDD), performance engineering, Core Web Vitals, security audits, and verification loops.",
    preferredRoutingProfile: "reasoning",
    allowedSkills: [
      "systematic-debugging",
      "debugging-strategies",
      "tdd-workflow",
      "code-optimizer",
      "performance-engineer",
      "web-quality",
      "webapp-testing",
      "security-review",
      "verification-loop",
      "verification-before-completion",
      "mattpocock-typescript",
    ],
    allowedCapabilities: [
      "search_vault",
      "read_note",
      "search_demo_data",
      "read_demo_item",
      "list_documents",
      "read_document",
    ],
    maxExecutionTimeMs: 60000,
    concurrencyLimit: 2,
    userVisible: true,
    isTemporary: false,
  },
  {
    id: "academic",
    displayName: "Academic & Writing Specialist",
    role: "Academic assignment structuring, essay formulation, systematic literature reviews, CS lab reports, citation formatting (IEEE, APA, Harvard, ACM), rubric auditing, and editorial polish.",
    preferredRoutingProfile: "reasoning",
    allowedSkills: [
      "academic-writer",
      "research-synthesist",
      "technical-report-writer",
      "academic-editor",
      "citation-specialist",
      "humanizer",
      "caveman",
    ],
    allowedCapabilities: [
      "search_vault",
      "read_note",
      "search_drive",
      "read_drive_file",
      "search_memory",
      "list_memory",
      "list_documents",
      "read_document",
      "write_document",
      "create_note",
    ],
    maxExecutionTimeMs: 60000,
    concurrencyLimit: 2,
    userVisible: true,
    isTemporary: false,
  },
  {
    id: "marketing",
    displayName: "Marketing & Growth Specialist",
    role: "Software launch strategies, conversion copywriting, technical documentation pitching, social media distribution (X/Twitter, LinkedIn), and technical SEO optimization.",
    preferredRoutingProfile: "fast",
    allowedSkills: [
      "growth-hacker",
      "tech-copywriter",
      "content-creator",
      "social-media-strategist",
      "seo-technical",
    ],
    allowedCapabilities: [
      "search_vault",
      "read_note",
      "search_memory",
      "list_memory",
      "list_documents",
      "read_document",
      "write_document",
      "create_note",
    ],
    maxExecutionTimeMs: 45000,
    concurrencyLimit: 2,
    userVisible: true,
    isTemporary: false,
  },
  {
    id: "architecture",
    displayName: "Architecture & Planning Specialist",
    role: "System architecture design, Socratic brainstorming, trade-off analysis, diagram generation (Excalidraw), codebase dependency mapping (graphify), and Vercel cloud deployment planning.",
    preferredRoutingProfile: "reasoning",
    allowedSkills: [
      "writing-plans",
      "brainstorming",
      "improve-codebase-architecture",
      "graphify",
      "excalidraw",
      "superpowers",
      "deploy-to-vercel",
    ],
    allowedCapabilities: [
      "search_vault",
      "read_note",
      "search_drive",
      "read_drive_file",
      "search_memory",
      "list_memory",
      "list_documents",
      "read_document",
    ],
    maxExecutionTimeMs: 60000,
    concurrencyLimit: 2,
    userVisible: true,
    isTemporary: false,
  },
];

