import type { IntentDefinition } from "@/lib/contracts/intent";

export const DEFAULT_INTENTS: readonly IntentDefinition[] = [
  {
    id: "cancel_run",
    description: "Abort or cancel the currently executing agent run or background task",
    aliases: [
      "stop",
      "cancel",
      "cancel this",
      "abort",
      "abort that",
      "cancel run",
      "stop execution",
      "halt",
      "cancel task",
      "stop it",
    ],
    channels: ["all"],
    priority: 100,
    safetyLevel: "safety_critical",
    confirmationRequired: false,
    handlerTarget: "task_controller",
    allowDeterministic: true,
    requiresContext: "active_run",
    active: true,
    examples: [
      "stop",
      "cancel this",
      "abort that",
      "cancel run",
      "stop execution",
    ],
    nonExamples: [
      "I don't want you to do that",
      "don't stop believing",
      "meaning of stop",
      "can you tell me how to stop a car",
    ],
  },
  {
    id: "stop_response",
    description: "Interrupt audio speech / voice synthesis immediately (barge-in)",
    aliases: [
      "be quiet",
      "quiet",
      "silence",
      "stop speaking",
      "stop talking",
      "hush",
      "shut up",
    ],
    channels: ["all"],
    priority: 95,
    safetyLevel: "safe",
    confirmationRequired: false,
    handlerTarget: "voice_playback",
    allowDeterministic: true,
    requiresContext: "none",
    active: true,
    examples: [
      "be quiet",
      "silence",
      "stop speaking",
      "stop talking",
    ],
    nonExamples: [
      "why is it quiet outside",
      "talking about books",
    ],
  },
  {
    id: "confirm_action",
    description: "Approve or confirm a pending write action",
    aliases: [
      "approve",
      "yes",
      "confirm",
      "proceed",
      "go ahead",
      "do it",
    ],
    channels: ["all"],
    priority: 90,
    safetyLevel: "safety_critical",
    confirmationRequired: true,
    handlerTarget: "confirmation_service",
    allowDeterministic: true,
    requiresContext: "active_confirmation",
    active: true,
    examples: [
      "approve",
      "yes",
      "confirm",
      "proceed",
    ],
    nonExamples: [
      "yes that was interesting",
      "confirming my attendance at conference",
      "do it yourself",
    ],
  },
  {
    id: "reject_action",
    description: "Reject or cancel a pending write action",
    aliases: [
      "reject",
      "deny",
      "disapprove",
      "cancel action",
      "reject this",
    ],
    channels: ["all"],
    priority: 90,
    safetyLevel: "safety_critical",
    confirmationRequired: false,
    handlerTarget: "confirmation_service",
    allowDeterministic: true,
    requiresContext: "active_confirmation",
    active: true,
    examples: [
      "reject",
      "deny",
      "cancel action",
    ],
    nonExamples: [
      "no problem",
      "deny access to hackers",
      "no worries",
    ],
  },
  {
    id: "undo_action",
    description: "Undo or revert the last completed reversible action",
    aliases: [
      "undo that",
      "revert that",
      "take it back",
      "undo last action",
      "undo",
      "revert",
    ],
    channels: ["all"],
    priority: 85,
    safetyLevel: "confirmation_required",
    confirmationRequired: true,
    handlerTarget: "task_controller",
    allowDeterministic: true,
    requiresContext: "reversible_action",
    active: true,
    examples: [
      "undo that",
      "revert that",
      "take it back",
      "undo",
    ],
    nonExamples: [
      "I don't want you to do that",
      "can you undo the knots",
      "revert to earlier plan in conversation",
    ],
  },
  {
    id: "get_time",
    description: "Check current server/local time and date (deterministic fast-path)",
    aliases: [
      "what time is it",
      "what is the time",
      "whats the time",
      "current time",
      "tell me the time",
      "what is the current time",
      "what is the current date and time",
      "what is the date and time",
      "what time is it right now",
      "time right now",
      "todays date and time",
      "current date and time",
    ],
    channels: ["all"],
    priority: 80,
    safetyLevel: "safe",
    confirmationRequired: false,
    handlerTarget: "tool:get_current_time",
    allowDeterministic: true,
    requiresContext: "none",
    active: true,
    examples: [
      "what time is it",
      "tell me the time",
      "what is the current time",
      "whats the time",
      "current time",
    ],
    nonExamples: [
      "time flies",
      "how many times did I do that",
      "what time do you usually sleep",
    ],
  },
  {
    id: "memory_save",
    description: "Capture and store facts, preferences, or notes into persistent local memory",
    aliases: [
      "remember this",
      "save this to memory",
      "don't forget this",
      "dont forget this",
      "keep this in mind",
      "store in memory",
      "remember that",
    ],
    channels: ["all"],
    priority: 75,
    safetyLevel: "safe",
    confirmationRequired: false,
    handlerTarget: "memory_service",
    allowDeterministic: false,
    requiresContext: "none",
    active: true,
    examples: [
      "remember this: my favorite color is navy",
      "don't forget this",
      "save this to memory",
      "keep this in mind",
    ],
    nonExamples: [
      "I remember that movie",
      "I'm talking about the word remember, not asking you to save anything",
      "do you remember what I said earlier",
      "remembering the past is natural",
    ],
  },
  {
    id: "memory_recall",
    description: "Search or query stored memories",
    aliases: [
      "what do you remember about",
      "recall",
      "what is in memory about",
      "search memory for",
      "search memories for",
    ],
    channels: ["all"],
    priority: 70,
    safetyLevel: "safe",
    confirmationRequired: false,
    handlerTarget: "memory_service",
    allowDeterministic: false,
    requiresContext: "none",
    active: true,
    examples: [
      "what do you remember about my project",
      "recall our discussion on rust",
      "search memory for key",
    ],
    nonExamples: [
      "I recall seeing a bird yesterday",
      "remember that movie we discussed",
    ],
  },
  {
    id: "capture_note",
    description: "Capture a note into the Obsidian vault",
    aliases: [
      "take a note",
      "capture note",
      "make a note",
      "write this down in notes",
      "save to notes",
      "put this in my notes",
      "record a note",
    ],
    channels: ["all"],
    priority: 75,
    safetyLevel: "confirmation_required",
    confirmationRequired: true,
    handlerTarget: "skill:capture-note",
    allowDeterministic: false,
    requiresContext: "none",
    active: true,
    examples: [
      "take a note about our release plan",
      "capture note: review pr 42",
      "make a note",
    ],
    nonExamples: [
      "note that the library is open",
      "I took note of what you said",
    ],
  },
  {
    id: "morning_briefing",
    description: "Prepare and present the morning daily briefing",
    aliases: [
      "morning briefing",
      "start my day",
      "what does my day look like",
      "brief me on today",
      "daily briefing",
    ],
    channels: ["all"],
    priority: 75,
    safetyLevel: "safe",
    confirmationRequired: false,
    handlerTarget: "skill:morning-briefing",
    allowDeterministic: true,
    requiresContext: "none",
    active: true,
    examples: [
      "morning briefing",
      "give me my morning briefing",
      "start my day",
      "brief me on today",
    ],
    nonExamples: [
      "good morning",
      "it was a quiet morning",
    ],
  },
  {
    id: "meeting_prep",
    description: "Prepare agenda, notes, and context for an upcoming meeting",
    aliases: [
      "meeting prep",
      "prep for my meeting",
      "prepare for next meeting",
      "prepare for meeting",
      "what do i need for my meeting",
    ],
    channels: ["all"],
    priority: 75,
    safetyLevel: "safe",
    confirmationRequired: false,
    handlerTarget: "skill:meeting-prep",
    allowDeterministic: true,
    requiresContext: "none",
    active: true,
    examples: [
      "meeting prep",
      "prep for my meeting with team",
      "prepare for next meeting",
    ],
    nonExamples: [
      "we had a meeting yesterday",
      "meeting room is on 2nd floor",
    ],
  },
  {
    id: "loose_ends",
    description: "Review unfinished items, action items, and pending tasks",
    aliases: [
      "loose ends",
      "what am i forgetting",
      "check for loose ends",
      "pending follow ups",
      "anything unfinished",
    ],
    channels: ["all"],
    priority: 75,
    safetyLevel: "safe",
    confirmationRequired: false,
    handlerTarget: "skill:loose-ends",
    allowDeterministic: true,
    requiresContext: "none",
    active: true,
    examples: [
      "check for loose ends",
      "what am I forgetting",
      "loose ends",
    ],
    nonExamples: [
      "tie up your shoelace ends",
    ],
  },
  {
    id: "research",
    description: "Perform research across vault notes and files",
    aliases: [
      "search my notes for",
      "research in vault",
      "find everything on",
      "research notes",
    ],
    channels: ["all"],
    priority: 70,
    safetyLevel: "safe",
    confirmationRequired: false,
    handlerTarget: "skill:research",
    allowDeterministic: false,
    requiresContext: "none",
    active: true,
    examples: [
      "search my notes for architecture",
      "research in vault on api design",
    ],
    nonExamples: [
      "research shows that sleep is important",
    ],
  },
  {
    id: "reminder_create",
    description: "Schedule a reminder (deferred/inactive capability in current phase)",
    aliases: [
      "remind me tomorrow",
      "set a reminder",
      "remind me at",
      "create a reminder",
      "remind me to",
    ],
    channels: ["all"],
    priority: 65,
    safetyLevel: "safe",
    confirmationRequired: false,
    handlerTarget: "scheduler",
    allowDeterministic: false,
    requiresContext: "none",
    active: false, // Inactive capability in Phase 07 per prompt specifications
    examples: [
      "remind me tomorrow at 8",
      "set a reminder for 5pm",
      "remind me to take medicine",
    ],
    nonExamples: [
      "that reminds me of yesterday",
      "a reminder is a good thing",
    ],
  },
];
